import { template } from 'solid-js/web';
import iconAward from '@/assets/icons_inline/iconAward.svg';
import iconConverge from '@/assets/icons_inline/iconConverge.svg';
import iconEarth from '@/assets/icons_inline/iconEarth.svg';
import iconHierarchy from '@/assets/icons_inline/iconHierarchy.svg';
import iconHome from '@/assets/icons_inline/iconHome.svg';
import iconMapPin from '@/assets/icons_inline/iconMapPin.svg';
import iconReticle from '@/assets/icons_inline/iconReticle.svg';
import iconSettings from '@/assets/icons_inline/iconSettings.svg';
import iconTools from '@/assets/icons_inline/iconTools.svg';

export const IconAward = template(iconAward);
export const IconConverge = template(iconConverge);
export const IconEarth = template(iconEarth);
export const IconHierarchy = template(iconHierarchy);
export const IconHome = template(iconHome);
export const IconMapPin = template(iconMapPin);
export const IconReticle = template(iconReticle);
export const IconSettings = template(iconSettings);
export const IconTools = template(iconTools);
